### ISSUE TITLE
Wrong Transaction Adress

### ISSUE THREAD

**Issue by agisinan** [Blockchair/Deleted-Issues#201]
Hi everyone!
İ m just wondering about what happens if someone transfers a crypto to a different crypto wallet adress ? For example transfering USTether to BTC wallet adress. What happens to that crypto assets ?
Thanks to you all 👍

**Comment by daria-blockchair** [comment]
Hi, 

If the USDT is on the Omni-layer and sent to a Bitcoin address, then the Bitcoin address manages the USDT. 

If the USDT is on the Ethereum network and sent to an Ethereum address, then the Ethereum address manages the USDT. 

Be careful here, because when USDT (or other tokens) are sent on the Ethereum network to an address on a different network, most likely the funds will be lost. There are some variations on this. Please check out our FAQ to learn more about incorrect transactions: https://blockchair.com/faq
