### ISSUE TITLE
0x70c96A85366Fa363ccA7636714a1F497e0714f56

### ISSUE THREAD

**Issue by Aminkavoos** [Blockchair/Deleted-Issues#542]
0x70c96A85366Fa363ccA7636714a1F497e0714f56

_Originally posted by @newlife08 in https://github.com/Blockchair/Deleted-Issues/issues/543

**Comment by newlife08** [comment]
> 0x70c96A85366Fa363ccA7636714a1F497e0714f56
> 
> _Originally posted by @newlife08 in https://github.com/Blockchair/Blockchair.Support/issues/1003#issuecomment-1287700329_

{"data":{"blocks":15803506,"transactions":1753398319,"blocks_24h":7164,"circulation_approximate":"122375301624480000000000000","transactions_24h":1050164,"difficulty":0,"volume_24h_approximate":"1424861972679062500000000","mempool_transactions":5097,"mempool_median_gas_price":13000000000,"mempool_tps":4.483333333333333,"mempool_total_value_approximate":"179353777559593080000","best_block_height":15802932,"best_block_hash":"9021e2084217939053c8478c393a44f2f6b7dd11023e6e5887d2001d950f1031","best_block_time":"2022-10-22 10:04:47","uncles":1306731,"uncles_24h":0,"blockchain_size":499480882045,"calls":5928203519,"average_transaction_fee_24h":"3316146733269172","median_transaction_fee_24h":"1426126961108050","inflation_24h":0,"average_simple_transaction_fee_24h":"649867784879614","median_simple_transaction_fee_24h":"517871403084000","burned":"2682971952368692566599277","burned_24h":"2913503292486325868965","largest_transaction_24h":{"hash":"0xe24e4afa0c259ab516eac6a87828751286ef6077844d55e1ed3de45964b183ae","value_usd":84430599.2563},"hashrate_24h":"0","inflation_usd_24h":0,"average_transaction_fee_usd_24h":4.316130780686491,"median_transaction_fee_usd_24h":1.8561755462301823,"average_simple_transaction_fee_usd_24h":0.8458354154100618,"median_simple_transaction_fee_usd_24h":0.6740355246839802,"market_price_usd":1301.55,"market_price_btc":0.067915874171304,"market_price_usd_change_24h_percentage":1.66856,"market_cap_usd":156957748343,"market_dominance_percentage":16.39,"layer_2":{"erc_20":{"tokens":464900,"transactions":1041669360,"tokens_24h":1099,"transactions_24h":779440},"erc_721":{"tokens":130849,"transactions":157920835,"tokens_24h":252,"transactions_24h":284048}},"countdowns":[{"event":"eth2 launch","eth_staked":14397772.007718565,"eth_needed":524288}],"suggested_transaction_fee_gwei_options":{"sloth":13,"slow":14,"normal":15,"fast":16,"cheetah":28},"addresses":0},"context":{"code":200,"source":"A","state":15802932,"state_layer_2":15802932,"market_price_usd":1301.55,"cache":{"live":false,"duration":"Ignore","since":"2022-10-22 10:04:51","until":"2022-10-22 10:06:02","time":2.1457672119140625e-6},"api":{"version":"2.0.95-ie","last_major_update":"2021-07-19 00:00:00","next_major_update":null,"documentation":"https:\/\/blockchair.com\/api\/docs","notice":":)"},"servers":"API4,ETH5,ETH5","time":0.9796760082244873,"render_time":0.0012958049774169922,"full_time":0.0012979507446289062,"request_cost":1}}

**Comment by newlife08** [comment]
> > 0x70c96A85366Fa363ccA7636714a1F497e0714f56
> > 
> > _Originally posted by @newlife08 in https://github.com/Blockchair/Blockchair.Support/issues/1003#issuecomment-1287700329_
> 
> {"data":{"blocks":15803506,"transactions":1753398319,"blocks_24h":7164,"circulation_approximate":"122375301624480000000000000","transactions_24h":1050164,"difficulty":0,"volume_24h_approximate":"1424861972679062500000000","mempool_transactions":5097,"mempool_median_gas_price":13000000000,"mempool_tps":4.483333333333333,"mempool_total_value_approximate":"179353777559593080000","best_block_height":15802932,"best_block_hash":"9021e2084217939053c8478c393a44f2f6b7dd11023e6e5887d2001d950f1031","best_block_time":"2022-10-22 10:04:47","uncles":1306731,"uncles_24h":0,"blockchain_size":499480882045,"calls":5928203519,"average_transaction_fee_24h":"3316146733269172","median_transaction_fee_24h":"1426126961108050","inflation_24h":0,"average_simple_transaction_fee_24h":"649867784879614","median_simple_transaction_fee_24h":"517871403084000","burned":"2682971952368692566599277","burned_24h":"2913503292486325868965","largest_transaction_24h":{"hash":"0xe24e4afa0c259ab516eac6a87828751286ef6077844d55e1ed3de45964b183ae","value_usd":84430599.2563},"hashrate_24h":"0","inflation_usd_24h":0,"average_transaction_fee_usd_24h":4.316130780686491,"median_transaction_fee_usd_24h":1.8561755462301823,"average_simple_transaction_fee_usd_24h":0.8458354154100618,"median_simple_transaction_fee_usd_24h":0.6740355246839802,"market_price_usd":1301.55,"market_price_btc":0.067915874171304,"market_price_usd_change_24h_percentage":1.66856,"market_cap_usd":156957748343,"market_dominance_percentage":16.39,"layer_2":{"erc_20":{"tokens":464900,"transactions":1041669360,"tokens_24h":1099,"transactions_24h":779440},"erc_721":{"tokens":130849,"transactions":157920835,"tokens_24h":252,"transactions_24h":284048}},"countdowns":[{"event":"eth2 launch","eth_staked":14397772.007718565,"eth_needed":524288}],"suggested_transaction_fee_gwei_options":{"sloth":13,"slow":14,"normal":15,"fast":16,"cheetah":28},"addresses":0},"context":{"code":200,"source":"A","state":15802932,"state_layer_2":15802932,"market_price_usd":1301.55,"cache":{"live":false,"duration":"Ignore","since":"2022-10-22 10:04:51","until":"2022-10-22 10:06:02","time":2.1457672119140625e-6},"api":{"version":"2.0.95-ie","last_major_update":"2021-07-19 00:00:00","next_major_update":null,"documentation":"https:\/\/blockchair.com\/api\/docs","notice":":)"},"servers":"API4,ETH5,ETH5","time":0.9796760082244873,"render_time":0.0012958049774169922,"full_time":0.0012979507446289062,"request_cost":1}}
> 0x70c96A85366Fa363ccA7636714a1F497e0714f56

**Comment by Aminkavoos** [comment]
#
![Uploading 1666093505782.jpg…]()

**Comment by Aminkavoos** [comment]
![1666645052186](https://user-images.githubusercontent.com/106019725/197912216-e54ac1d2-7aa9-4165-bb38-230b75c86ae5.jpg)
![Screenshot_۲۰۲۲۱۰۲۴-۰۰۵۱۳۸_Edge](https://user-images.githubusercontent.com/106019725/197912222-950486ec-70cd-46a7-bcb4-cf1f84a1825f.jpg)
![horizontal_blue](https://user-images.githubusercontent.com/106019725/197912224-764d3eb8-70d6-49ce-8bc5-5d5efb907e6a.png)

**Comment by Aminkavoos** [comment]
> 0x70c96A85366Fa363ccA7636714a1F497e0714f56
> 
> _Originally posted by @newlife08 in https://github.com/Blockchair/Deleted-Issues/issues/543

**Comment by Aminkavoos** [comment]
> #
> ![Uploading 1666093505782.jpg…]()
>

**Comment by newlife08** [comment]
> 0x70c96A85366Fa363ccA7636714a1F497e0714f56
