### ISSUE TITLE
Sent Bitcoin not received 

### ISSUE THREAD

**Issue by Tomkidash** [Blockchair/Deleted-Issues#666]
I sent $500 btc to the right wallet since two day now and the recipient is yet to receive it but it has more than 20 confirmation please help

**Comment by dankdanimal** [comment]
I used cashapp to cash out 1483 from stake.us like I always do. They rejected it causing me to have to do a reversal which to stake looks like you just bought a bunch of casino money. Made it so I couldn't cash out the 1583 it turned into since I was playing games just because I thought I had to to get my money down. Ok and then I cash it out to my other BTC wallet. When I went to send it back to cashapp, they changed my fucking BTC address on me causing me to send all that money nowhere which means what? I'm really hoping it just dies in the block chain and automatically refunds to me.

**Comment by dankdanimal** [comment]
Ty I will try him.

**Comment by daria-blockchair** [comment]
Hi @Tomkidash, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

If a BTC transaction has over 20 confirmations, then the coins are at the receiving address. Please reach out to the receiving wallet or exchange for more information and to find out when the funds will be credited to the account.

**Comment by daria-blockchair** [comment]
Dear @dankdanimal, 

Unfortunately, we are not able to help get your money back. Please contact your wallet for more information and further assistance. 

Thank you for understanding.
