### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Sherrysoto76** [Blockchair/Deleted-Issues#799]
It has been over two weeks and my transaction still is not verified. How much longer am I going to have to wait. This is ridiculous.

**Comment by pcgandhinj466** [comment]
Hello,

Thank you for reaching out to us regarding the delay in verifying your
transaction.

We apologize for any inconvenience this may have caused you. Rest assured,
our team is working diligently to address your concern and expedite the
verification process. However, please note that due to high volumes of
transactions, there has been a slight delay in our usual response times.

We understand your frustration and we genuinely appreciate your patience.
We will make every effort to resolve this matter as quickly as possible.

Should you have any further questions or require additional assistance,
please do not hesitate to let us know. We value your business and are
committed to ensuring your satisfaction.

Best regards,

[Your Name]

**Comment by Danyalkasiri** [comment]
[]()

**Comment by Sherrysoto76** [comment]
It's been 3 weeks now and it is still not verified. This is getting to be
very upsetting.

**Comment by daria-blockchair** [comment]
> It has been over two weeks and my transaction still is not verified. How much longer am I going to have to wait. This is ridiculous.

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
